### ISSUE TITLE
Conflicto entre componentes LazSolutionDT y Sdpo

### ISSUE THREAD

**Issue by pelecho** [silvioprog/lazsolutions#15]
Hola.
Estoy usando los componentes LazSolution y al intentar instalar los sdpo, crea conflictos y no me instala. El conflicto es porque ambos paquetes usan alguna rutinas iguales en directorios distintos.

Es que necesito leer datos con lazarus desde el puerto serial y bajo linux (ubuntu 12.04) según entiendo es la única solucion.

Talvez habrá la forma de leer el puerto serial con una rutina sin usar usar componentes?

Gracias de antemano por la ayuda, saludos,
Orlando

**Comment by silvioprog** [comment]
Se o problema persistir adicione o Sdpo como dependência LazSolutions ou vice-versa.
