### ISSUE TITLE
TLSExpandPanel - Access Violation ao Clicar no botão Expand

### ISSUE THREAD

**Issue by vansiqq** [silvioprog/lazsolutions#16]
Se o componente estiver com o Align = AlLeft e expandido, ao clicar no botão Expand, gera um erro de Acess Violation.

Ambiente: Linux Mint 14 32 bits, Lazarus 1.1 SVN FPC 2.71

**Comment by silvioprog** [comment]
Não sei se o problema persiste em versões mais recentes do Lazarus, no entanto, como estou pensando seriamente em reescrever o LazSolutions, todos esses bugs serão extintos.
