### ISSUE TITLE
Ghost process after calling LSPlayWav in async mode

### ISSUE THREAD

**Issue by talexone** [silvioprog/lazsolutions#17]
Hello,

I have an issue on debian wheezy when calling lsplaywav in async mode, aplay process stay in memory after playing sound. Each time I play sound a new process created and stay in memory. I don't know if it's really harmeless if the quantity of ghost process will be above a thousand.

 3545 pts/2    00:00:00 aplay &lt;defunct&gt;

Any idea how to terminate these ghost process without restarting main app.

Regards,
Alex
Platform: debian wheezy 32bit/lazarus 1.2.6./fpc 2.6.4

**Comment by silvioprog** [comment]
Feel free to send any patch solving it!
