### ISSUE TITLE
placeholder não funciona em alguns componentes

### ISSUE THREAD

**Issue by franciscoluiz** [silvioprog/lazsolutions#6]
O placeholder está 100% para o lsedit, lseditbutton e lsgadgetedit.

Mas nao funciona no lsmemo, lsmaskedit, lsnumericedit e no lscurrencyedit...
O placeholder não esta aparecendo nem em design nem em execução. Exceto o placeholder do lsmaskedit, que funciona em execução.

Exemplo para teste: http://www.sendspace.com/file/zdfnem

**Comment by silvioprog** [comment]
Se não me engano estes recursos já estão disponíveis nos componentes padrões da LCL. Estou pensando seriamente em reviver o projeto LazSolutions trazendo novos conceitos de desenvolvimento desktop para ele, e provavelmente implementando algo para ele conseguir consumir APIs online de maneira mais moderna. Se tudo der certo a suíte será reescrita do zero, provavelmente mudando até de nome. :-)
