### ISSUE TITLE
Where is crptlib.pas

### ISSUE THREAD

**Issue by SamHu** [silvioprog/lazsolutions#9]
When I compile and install the package to fpc2.6.0+laz IDE 1.02,got message:
..\3rdParty\Synapse\ssl_cryptlib.pas(0,0) Fatal: Can not find unit cryptlib used by ssl_cryptlib.

in ssl_cryptlib.pas it uses unit crptlib.pas,but I can't find it everywhere inside the package and also inside Lazarus.

Help would be appreicated.

Regards,
Sam

**Comment by silvioprog** [comment]
Nice! :-)

**Comment by sergiocontreras** [comment]
Hum need to get back to Lazarus ... haven't played with it for a while ... missed the message two years ago LOL

**Comment by silvioprog** [comment]
I left the desktop development years ago, now I came back.
